[package]
name = "image_veracity"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/image-veracity", "crates/trillian"]

[[bin]]
name = "image-veracity"
path = "crates/image-veracity"