version: '3.1'
services:
  roach-single:
    hostname: roach-single
    image: cockroachdb/cockroach:v23.1.3
    environment:
      - COCKROACH_DATABASE=test
      - COCKROACH_USER=test
      - COCKROACH_PASSWORD=zaphod
    restart: always # keep the CRDB server running
    volumes:
      - "./crdb/data/:/cockroach/cockroach-data/"
      - "./crdb/docker-entry-point-initdb.d/:/cockroach/cockroach-data/docker-entry-point-initdb.d/"
    ports:
      - "26257:26257"
      - "8081:8081"
    command:
      - start-single-node
      - --http-addr=roach-single:8081
      - --insecure
  trillian-log-server:
    build:
      context: ../proto/trillian
      dockerfile: ../../deploy/Dockerfile
      args:
        - GOFLAGS
    command: [
      "/trillian_log_server",
      "--storage_system=crdb",
#      "--crdb_uri=postgresql://zaphod@roach-single:26257/veracity?sslmode=verify-full&sslrootcert=/root.crt",
      "--crdb_uri=postgresql://root@roach-single:26257/veracity?sslmode=disable",
      "--quota_system=crdb",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--alsologtostderr",
    ]
    restart: always # retry while mysql is starting up
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - roach-single
  trillian-log-signer:
    build:
      context: ../proto/trillian
      dockerfile: ../../deploy/Dockerfile
      args:
        - GOFLAGS
    command: [
      "/trillian_log_signer",
      "--storage_system=crdb",
#      "--crdb_uri=postgresql://zaphod@roach-single:26257/veracity?sslmode=verify-full&sslrootcert=/root.crt",
      "--crdb_uri=postgresql://root@roach-single:26257/veracity?sslmode=disable",
      "--quota_system=crdb",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--force_master",
      "--alsologtostderr",
    ]
    restart: always # retry while mysql is starting up
    ports:
      - "8092:8091"
    depends_on:
      - roach-single
